# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: gomod
  directory: /
  groups:
    all-go-deps:
      patterns:
        - "*"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: ":seedling:"
    include: "scope"
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    all-gha-deps:
      patterns:
        - "*"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling:"
    include: "scope"

- package-ecosystem: docker
  directory: /cmd
  schedule:
    interval: weekly
  ignore:
    versions:
      - "> 1.22.99" # Only allow updates that are 1.22.x
