Witnesses:
  - ArmoredWitness-autumn-wood+863571a5+AesIVCbad7gbU07JnA6YfZD0qg4B1c8xF4ISdnt9vjip
  - ArmoredWitness-dry-sunset+ae83a8fa+AQPzi+erfxCBvjk6nmndWU2aGEoO7zawoatven8Fvv/D
  - ArmoredWitness-floral-sky+504ec40f+AekCmTmKTTnQMNqIigkj7PFnhogawSJD23PJ8M8qLYDm
  - ArmoredWitness-hidden-river+45a41ba7+AdrpNMfMH0W6iYo9/hJl1JKmxYQF3ewUP8FvhKD1iOOl
  - ArmoredWitness-icy-sun+7bb3d795+AflD2IuT6uOo8vzXcY2e088bmm9hjzPVmHHVrDhfmxHF
  - ArmoredWitness-morning-darkness+2a654a97+AXugA2VGdDmLYt1wqzaaP3UKSGcDVNZveRJYJ1FKC5+9
  - ArmoredWitness-nameless-firefly+1a0b2617+AQdRiZgMwTiPqGhsdDICiBLeMYLiV+IZRj988o1J1XPd
  - ArmoredWitness-quiet-wood+6a554a5d+AZtxeZvnMbFf6bVPN81vIvlJnT4zCdq8tYi/guI0hEkT
  - ArmoredWitness-rough-wind+ded3ae66+Aeoxk0r7hjKVjeL7N92b+ruNx5Yd6memrkxX8aHKJu73
  - ArmoredWitness-shy-wind+e76ed9ec+ARmL7SaHvPYPwkbq41g/KpdkKH7OZaoaqfK2sEoWKL4d
  - ArmoredWitness-small-breeze+7b3ada3a+AQAWYpUjfGGPQiWOgt6sLWap0P9rVOe+Ofu2uNZbO4FD
  - ArmoredWitness-snowy-sound+c701f2ec+AQuFudRsy9HPp4oZsE+PxDWVODkMnYJnXonSQzIXqq1Q
  - ArmoredWitness-throbbing-bird+13664818+AZgUml1zmzuqd3Eo9hdTHOi2VNJFAqfhUSRMxbdZdme8
  - ArmoredWitness-wispy-wood+90626287+AUVvZZ4LDvpljjooleJ3WnxnVK4J1YQiQbtgPWSVFwaP
  - ArmoredWitness-weathered-rain+ea3d386d+AWLblKp5JuiyrgRh6ev2nNJ5XAd+sc/mM2D2HW/b4d5S
